# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='has_been_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
